REPO = $(HOME)/CS2GitAssignment/sources
INCLUDES= -I $(HOME)/CS2GitAssignment/headers

excu: main.cpp $(REPO)/mark.cpp $(REPO)/mariam.cpp
	g++ $(INCLUDES) main.cpp $(REPO)/mark.cpp $(REPO)/mariam.cpp -o excu
